#!/bin/sh
# -----------------------------------------------------------------
# CatIO Network tinc-up hook script
#
# Description: This script was called when tinc started
#
# Auther: Grover Chou <groverchout@gmail.com>
#         Icecat
# -----------------------------------------------------------------

VERSION=2.1.1

# --- Settings ----------------------------------------------------

address_v4=
address_v6=
gateway_v6=
#default_route_v6=true

# --- Initialize --------------------------------------------------

set -o errexit
export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin

# --- Process -----------------------------------------------------

echo "CatIO Network tinc-up script version $VERSION"

## Interface

echo "Setting interface"

if [ -n "$address_v4" ]
then
    ip address add $address_v4 dev $INTERFACE
fi

if [ -n "$address_v6" ]
then
    ip -6 address add $address_v6 dev $INTERFACE
fi

ip link set $INTERFACE up

## Default route

echo "Setting default route"
# Why is it so violent that coexistence is not good?
ip -6 r a 2000::/3 via $gateway_v6 dev $INTERFACE metric 1025

#if [ "$default_route_v6" = true ] && [ -n "$gateway_v6" ]
#then
#    original_gateway_v6=$(ip -6 route | awk '/default/ { print $3 }')
#
#    if [ -n "$original_gateway_v6" ]
#    then
#        ip -6 route del default
#    fi
#
#    ip -6 route add default dev $INTERFACE via $gateway_v6
#fi

# --- Extra -------------------------------------------------------
